#! /usr/bin/env sh

MARKDOWN_FILES=$(find . -type f -iname "*.MD" | sort)

if [ -f README.md ]; then
        generate-header README.md
fi


for md_file in $MARKDOWN_FILES; do
        if [ ! -f README.md ]; then
                generate-header $md_file
                echo "<body>"
        fi
        markdown $md_file
        if [ ! -f README.md ]; then
                echo "</body>"
        fi
done

